[package]
name = "wolf-raycaster"
version = "0.1.0"
edition = "2021"
authors = ["Edward Shaw"]
license = "MIT"

[dependencies]
cgmath = "0.16.0"
lodepng = "2.0.0"
rgb = "0.8"
freetype-rs = "0.19.0"

[dependencies.sdl2]
version = "0.31"
features = ["image"]
